source 'git@gitlab-ee.jiamiantech.com:zy/architecture/ios/jiamianspecs.git'
source 'https://mirrors.bfsu.edu.cn/git/CocoaPods/Specs.git'

platform :ios, '13.0'

target 'BoxAttemptDemo' do
  pod 'BoxAttemptSDK', :path => '../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
end
